[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sum_parts"
path = "src/sum_parts.rs"

[[bin]]
name = "sum_gears"
path = "src/sum_gears.rs"

[dependencies]
itertools = "0.12.0"
